version: "3.8"

services:
  elasticsearch:
    build:
      dockerfile: .docker/Dockerfile
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./.rag_data/es_data:/usr/share/elasticsearch/data

  qdrant:
    image: qdrant/qdrant:v1.11.3
    container_name: qdrant
    ports:
      - "6333:6333" # Dashboard: http://localhost:6333/dashboard
    volumes:
      - ./.rag_data/qdrant_data:/qdrant/storage

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0 # Elasticsearchと同じバージョンに合わせる
    container_name: kibana
    ports:
      - 5601:5601 # Dashboard: http://localhost:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Elasticsearchサービス名とポート
    depends_on:
      - elasticsearch
